# @package _global_
model:
  charset_train: >
    ি ৄ ু ৗ ো ৈ ৌ ঁ ৃ া ় ঃ ূ ে ং ী ্আৱ২৷দবঠম৬৺ঌখঘঢষউঋয৵ফচকঊরতঔঙইঞওণনভয়৴ট৪ৡথ০১ঀঝৠ৶ড়ঈলছ৮এ৸৲অৎজধগ৫ৰঽঢ়৳প৩ড৭৹শঐসহ৯৻
    ા ૉ ૢ િ ઁ ી ો ૌ ૂ ૅ ુ ં ્ ઃ ૃ ે ૄ ઼ૈઽઢ૰યઆણઋઐૡમનવઇથઔઞઅ૦ટ૪જચઑગલછૐ૮તપઍશફઘ૬ક૭રખ૫ૠસધદષઌ૨ભળહબઊઉ૯૩ઝ૧ઠડઈએઙઓ
    ् ः ॄ ऺ ॓ ॑ ँ ॅ ृ ़ ी ा ो ि ै ॔ ॣ े ु ॆ ं ौ ू ॉ ॊ ॖ ॢ ॒धभयओझॲ५ॡऱ३०॥ॠनऔळ७म८चऋअऴणॻतॾ९कह।ञष४ऎऐस६गइॐङघथऒडउखएईदऌलऽॱ२बऊऩवटछश१रजढऍपआ॰ॿठफऑ
    ು ಃ ೕ ೖ ೄ ೀ ೊ ೋ ೇ ಿ ್ ೈ ಂ ಼ ೆ ಾ ೂ ೃ ೌೡಖಯಐಢಙಠಮಉಫವಞಒ೭ಷ೫ಅಟಈ೨ಜಳಭಸಘ೩ಕಊಧ೯ನ೧ಽಋಲ೬ಣ೦ಏಓಡ೮ಬಌರಆಗಹಛಥಎಶಱಝದ೪ೞತಪಚೠಔಇ
    ി ൗ ൢ ് ൃ ൄ ോ െ ൈ ീ ൊ ൌ ു ൂ ാ േദന ഃഌഎറഽഐഋഈഓണടധഇഘഠ൯ള൹൧ലത൬൪൭ഊങൻവ൦ശജഞൠൡഏൽ൫ഩആഥബഭഔൾഗഒഫഡ൮ൿഷമചഴകയസഛഉ൩ഹഺഢഖപഅൺർരഝ൨ ം൳൲൴൵൰ൟ
     ै ॒ ि ृ ् ़ ॅ ॉ ी ं ू ा ँ ो े ु ः ौ१य7त6ई८ण?82।हधज९४ऐसगछ॥चभ-कपऊनख3थव5ळइशअष9ट६७डऑलझफउ!ब०३आठ५|२0द4ञ1मएरढओऱघॐऍॺऋॸ
     ଃ ୍ ି ା ୗ ୂ ୌ ଼ ୁ ୋ ଁ େ ୖ ୀ ୈ ୃ ଂ ୄ ୢ ୣହଋଌ୧ଫଢୠତ୨ବ୪ଞ୬ଣଭଡଵୱ୮ଔସଘଠନଥୟ୭ଝଧ୰ପଖଇରମଷଚ୫ଉଆଶଽଦଏଈଟଓ୯ଊୡକଯଅଐଜଳଲଙ୦୩ଛଗ୶୵୴୳୷ଡ଼୲ଢ଼
     ਃ ਂ ੂ ੍ ੱ ੋ ੵ ੈ ਾ ਿ ੑ ੌ ੰ ੁ ਁ ੇ ੀ ਼ੜਬਮਊਥ੩ਣਅਜਟਆਝੳਞਏਓਠਇ੯੦ਦਗਛਙਵਲਕ੬ਚ੧ਔਹ੨ਐੴਖਫਧ੪ਸਨਈਡ੫ੲ੭੮ਢਉਸ਼ਭਰਪਯਘਤਖ਼ਲ਼ਜ਼ਗ਼ਫ਼
    ௗ ொ ி ு ே ெ ஂ ை ் ூ ீ ோ ா ௌஈள௦ஷக௭௵ஓஅ௧ணஞயடவனஊதபலஹஒஔ௯இஃ௱ஐ௹ரஎ௪மஜஏஆ௨ஸஉ௮௰௫ற௩சநழஙஶ௲௳௬௴௺ௐ௸௶௷
    ఁ ౄ ె ౌ ొ ృ ూ ః ్ ం ా ౖ ు ి ో ే ీ ైఘడ౦ఆఇష౧ఱ౭ట౫ఔౡ౬ఋఢ౨ళఉఝనఙఖజశఞసవగఛఐఅలఒఏఫధఓౠ౩కతఴరఎబచణఊఠఈయ౪థహభఌదపమ౮౯
    . ,:()
    ढ़
    ड़
    ज़

  charset_test: >
    ি ৄ ু ৗ ো ৈ ৌ ঁ ৃ া ় ঃ ূ ে ং ী ্আৱ২৷দবঠম৬৺ঌখঘঢষউঋয৵ফচকঊরতঔঙইঞওণনভয়৴ট৪ৡথ০১ঀঝৠ৶ড়ঈলছ৮এ৸৲অৎজধগ৫ৰঽঢ়৳প৩ড৭৹শঐসহ৯৻
    ા ૉ ૢ િ ઁ ી ો ૌ ૂ ૅ ુ ં ્ ઃ ૃ ે ૄ ઼ૈઽઢ૰યઆણઋઐૡમનવઇથઔઞઅ૦ટ૪જચઑગલછૐ૮તપઍશફઘ૬ક૭રખ૫ૠસધદષઌ૨ભળહબઊઉ૯૩ઝ૧ઠડઈએઙઓ
    ् ः ॄ ऺ ॓ ॑ ँ ॅ ृ ़ ी ा ो ि ै ॔ ॣ े ु ॆ ं ौ ू ॉ ॊ ॖ ॢ ॒धभयओझॲ५ॡऱ३०॥ॠनऔळ७म८चऋअऴणॻतॾ९कह।ञष४ऎऐस६गइॐङघथऒडउखएईदऌलऽॱ२बऊऩवटछश१रजढऍपआ॰ॿठफऑ
    ು ಃ ೕ ೖ ೄ ೀ ೊ ೋ ೇ ಿ ್ ೈ ಂ ಼ ೆ ಾ ೂ ೃ ೌೡಖಯಐಢಙಠಮಉಫವಞಒ೭ಷ೫ಅಟಈ೨ಜಳಭಸಘ೩ಕಊಧ೯ನ೧ಽಋಲ೬ಣ೦ಏಓಡ೮ಬಌರಆಗಹಛಥಎಶಱಝದ೪ೞತಪಚೠಔಇ
    ി ൗ ൢ ് ൃ ൄ ോ െ ൈ ീ ൊ ൌ ു ൂ ാ േദന ഃഌഎറഽഐഋഈഓണടധഇഘഠ൯ള൹൧ലത൬൪൭ഊങൻവ൦ശജഞൠൡഏൽ൫ഩആഥബഭഔൾഗഒഫഡ൮ൿഷമചഴകയസഛഉ൩ഹഺഢഖപഅൺർരഝ൨ ം൳൲൴൵൰ൟ
     ै ॒ ि ृ ् ़ ॅ ॉ ी ं ू ा ँ ो े ु ः ौ१य7त6ई८ण?82।हधज९४ऐसगछ॥चभ-कपऊनख3थव5ळइशअष9ट६७डऑलझफउ!ब०३आठ५|२0द4ञ1मएरढओऱघॐऍॺऋॸ
     ଃ ୍ ି ା ୗ ୂ ୌ ଼ ୁ ୋ ଁ େ ୖ ୀ ୈ ୃ ଂ ୄ ୢ ୣହଋଌ୧ଫଢୠତ୨ବ୪ଞ୬ଣଭଡଵୱ୮ଔସଘଠନଥୟ୭ଝଧ୰ପଖଇରମଷଚ୫ଉଆଶଽଦଏଈଟଓ୯ଊୡକଯଅଐଜଳଲଙ୦୩ଛଗ୶୵୴୳୷ଡ଼୲ଢ଼
     ਃ ਂ ੂ ੍ ੱ ੋ ੵ ੈ ਾ ਿ ੑ ੌ ੰ ੁ ਁ ੇ ੀ ਼ੜਬਮਊਥ੩ਣਅਜਟਆਝੳਞਏਓਠਇ੯੦ਦਗਛਙਵਲਕ੬ਚ੧ਔਹ੨ਐੴਖਫਧ੪ਸਨਈਡ੫ੲ੭੮ਢਉਸ਼ਭਰਪਯਘਤਖ਼ਲ਼ਜ਼ਗ਼ਫ਼
    ௗ ொ ி ு ே ெ ஂ ை ் ூ ீ ோ ா ௌஈள௦ஷக௭௵ஓஅ௧ணஞயடவனஊதபலஹஒஔ௯இஃ௱ஐ௹ரஎ௪மஜஏஆ௨ஸஉ௮௰௫ற௩சநழஙஶ௲௳௬௴௺ௐ௸௶௷
    ఁ ౄ ె ౌ ొ ృ ూ ః ్ ం ా ౖ ు ి ో ే ీ ైఘడ౦ఆఇష౧ఱ౭ట౫ఔౡ౬ఋఢ౨ళఉఝనఙఖజశఞసవగఛఐఅలఒఏఫధఓౠ౩కతఴరఎబచణఊఠఈయ౪థహభఌదపమ౮౯
    . ,
    ढ़
    ड़
    ज़